const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const now = new Date();

// Helper date offsets
const daysAgo = (d) => new Date(Date.now() - d * 86400000);
const daysAhead = (d) => new Date(Date.now() + d * 86400000);

const sampleJobs = [
  {
    slug: "indian-postal-gds-recruitment-2026",
    post_name: "GDS, BPM, ABPM",
    organization_name: "India Post (Department of Posts)",
    department: "Ministry of Communications",
    government_field: "Postal",
    slug: "ssc-chsl-recruitment-2026",
    post_name: "Lower Division Clerk / Junior Secretariat Assistant",
    organization_name: "Staff Selection Commission",
    department: "Department of Personnel and Training (DoPT)",
    government_field: "SSC",
    government_level: "Central Government",
    state: "All India",
    qualification: "10th Pass with Computer Knowledge & Local Language",
    qualification: "12th Pass",
    qualification_level: "12TH",
    qualification_details: "12th Standard or Equivalent examination from recognized Board/University",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 3500,
    salary_min: 19900,
    salary_max: 63200,
    salary_text: "₹19,900 – ₹63,200",
    age_min: 18,
    age_max: 27,
    age_relaxation: "Age relaxation as per government rules (SC/ST: 5 Yrs, OBC: 3 Yrs, PwD: 10 Yrs)",
    selection_process: "Tier-I (Computer Based Test), Tier-II (Computer Based Test), Skill Test / Typing Test (where applicable)",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹100",
    application_fee_general: "₹100",
    application_fee_ews: "₹100",
    application_fee_female: "₹0 (as per notification)",
    application_fee_pwd: "₹0",
    application_fee_other: "EWS: ₹100, Female: ₹0 (as per notification)",
    notification_date: daysAgo(20),
    start_date: daysAgo(15),
    last_date: daysAhead(25), // Open
    exam_date: daysAhead(60),
    admit_card_date: daysAhead(50),
    result_date: null,
    official_website: "https://ssc.gov.in",
    official_notification_url: "https://ssc.gov.in/notice-modal/CHSL_2026_Notice.pdf",
    application_url: "https://ssc.gov.in/portal/login",
    job_description: "Staff Selection Commission (SSC) invites online applications for Combined Higher Secondary (10+2) Level Examination 2026 for recruitment to Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), and Data Entry Operator (DEO) in various Ministries, Departments, and Constitutional Offices.",
    eligibility: "Candidates must have passed 12th Standard or equivalent examination from a recognized Board or University. For DEO in CAG office: 12th Standard pass in Science stream with Mathematics.",
    required_documents: "1. 10th & 12th Certificate\n2. Live Webcam Photo capture as per SSC norms\n3. Signature scan (10 to 20 KB)\n4. Photo Identity Proof (Aadhaar/Voter ID/PAN)\n5. Category Certificate",
    how_to_apply: "1. Visit official website ssc.gov.in\n2. Complete One Time Registration (OTR)\n3. Fill online application form for CHSL 2026\n4. Upload live photograph and signature\n5. Pay fee of ₹100 online (if applicable)\n6. Submit and print application form",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "railway-group-d-recruitment-2026",
    post_name: "Railway Group D Recruitment 2026",
    organization_name: "Indian Railways",
    department: "Ministry of Railways (RRB)",
    government_field: "Railway",
    government_level: "Central Government",
    state: "All India",
    qualification: "10th/12th Pass or ITI",
    qualification_level: "10TH",
    qualification_details: "10th Pass (Matriculation) or ITI from NCVT/SCVT recognized institution",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 23757,
    salary_min: 10000,
    salary_max: 30000,
    salary_text: "₹10,000 – ₹30,000 (TRCA Slab)",
    number_of_posts: 32438,
    salary_min: 18000,
    salary_max: 56900,
    salary_text: "₹18,000 – ₹56,900",
    age_min: 18,
    age_max: 40,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 Years, EWS: No Relaxation",
    selection_process: "Merit List based on Class 10th Marks, No Exam, No Interview",
    application_fee_sc_st: "₹0/- (Exempted)",
    application_fee_obc: "₹100/-",
    application_fee_general: "₹100/-",
    application_fee_other: "PwD/Female: ₹0/- (Exempted), EWS: ₹100/-",
    notification_date: new Date("2026-08-25"),
    start_date: new Date("2026-09-02"),
    last_date: new Date("2026-09-24"), // Closing soon!
    exam_date: null,
    admit_card_date: null,
    result_date: new Date("2026-10-15"),
    official_website: "https://www.indiapost.gov.in",
    official_notification_url: "https://indiapostgdsonline.gov.in/Notifications/GDS_Recruitment_2026.pdf",
    application_url: "https://indiapostgdsonline.gov.in",
    job_description: "Department of Posts has released the official recruitment notification for Gramin Dak Sevaks (GDS), Branch Postmaster (BPM), and Assistant Branch Postmaster (ABPM) across all postal circles nationwide.",
    eligibility: "Secondary School Examination pass certificate of 10th standard with passing marks in Mathematics and English conducted by any recognized Board of School Education. The candidate should have studied the local language at least up to 10th standard. Basic computer training certificate of at least 60 days duration is desirable.",
    required_documents: "1. 10th Marks Memo/Certificate\n2. Passport Size Photograph (up to 50KB, JPG)\n3. Signature (up to 20KB, JPG)\n4. Community/Caste Certificate (SC/ST/OBC/EWS)\n5. PwD Certificate (if applicable)\n6. Aadhar Card or Valid ID Proof",
    how_to_apply: "1. Visit official website indiapostgdsonline.gov.in\n2. Complete initial Registration with Mobile number and Email\n3. Fill online application form and upload scanned documents\n4. Select Circle and Post Preferences\n5. Pay application fee online (if applicable)\n6. Submit and download the confirmation page",
    age_max: 33,
    age_relaxation: "OBC: 3 Years, SC/ST: 5 Years, PwD: 10 Years",
    selection_process: "Computer Based Test (CBT), Physical Efficiency Test (PET), Document Verification & Medical Examination",
    application_fee_sc_st: "₹250 (Refundable)",
    application_fee_obc: "₹500 (₹400 Refundable)",
    application_fee_general: "₹500 (₹400 Refundable)",
    application_fee_ews: "₹500 (₹400 Refundable)",
    application_fee_female: "₹250 (Refundable)",
    application_fee_pwd: "₹250 (Refundable)",
    application_fee_other: "Women, Ex-SM, Transgender, Minorities & EBC: ₹250/-",
    notification_date: daysAgo(30),
    start_date: daysAgo(20),
    last_date: daysAhead(2), // CLOSING SOON (within 3 days)
    exam_date: daysAhead(45),
    admit_card_date: daysAhead(35),
    result_date: null,
    official_website: "https://www.rrbapply.gov.in",
    official_notification_url: "https://www.rrbapply.gov.in/notices/CEN_GroupD_2026.pdf",
    application_url: "https://www.rrbapply.gov.in",
    job_description: "Railway Recruitment Boards (RRB) invite online applications for 32,438 Level-1 (Group D) posts including Track Maintainer Grade-IV, Pointsman, Assistant Workshop across 16 Zonal Railways.",
    eligibility: "10th pass from recognized board OR National Apprenticeship Certificate (NAC) granted by NCVT OR 10th pass plus ITI.",
    required_documents: "1. 10th Standard Certificate\n2. ITI / NAC Certificate (if applicable)\n3. Digital Photo & Signature\n4. Caste / EWS Certificate",
    how_to_apply: "1. Visit rrbapply.gov.in\n2. Create an account with Mobile and Email\n3. Select RRB zone and post preference\n4. Submit educational details and upload documents\n5. Pay examination fee and download receipt",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "ssc-chsl-recruitment-2026",
    post_name: "Lower Division Clerk / JSA, Data Entry Operator",
    organization_name: "Staff Selection Commission (SSC)",
    department: "Department of Personnel and Training (DoPT)",
    slug: "ssc-mts-recruitment-2026",
    post_name: "SSC MTS Recruitment 2026",
    organization_name: "Staff Selection Commission",
    department: "Department of Personnel and Training",
    government_field: "SSC",
    government_level: "Central Government",
    state: "All India",
    qualification: "12th Standard or Equivalent examination from recognized Board",
    qualification_level: "12TH",
    qualification: "10th Pass",
    qualification_level: "10TH",
    qualification_details: "Matriculation (10th Standard) Pass from a recognized Board",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 3712,
    salary_min: 19900,
    salary_max: 63200,
    salary_text: "₹19,900 – ₹63,200 (Pay Level 2 & 4)",
    number_of_posts: 9583,
    salary_min: 18000,
    salary_max: 56900,
    salary_text: "₹18,000 – ₹56,900",
    age_min: 18,
    age_max: 27,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 Years, Ex-SM: 3 Years",
    selection_process: "Tier-I (CBT Objective), Tier-II (CBT + Typing / Skill Test), Document Verification",
    application_fee_sc_st: "₹0/-",
    application_fee_obc: "₹100/-",
    application_fee_general: "₹100/-",
    application_fee_other: "Women candidates and candidates belonging to SC, ST, PwD and ESM: ₹0/-",
    notification_date: new Date("2026-08-28"),
    start_date: new Date("2026-09-01"),
    last_date: new Date("2026-09-25"), // Closing soon!
    exam_date: new Date("2026-11-15"),
    admit_card_date: new Date("2026-11-05"),
    age_relaxation: "SC/ST: 5 Yrs, OBC: 3 Yrs, PwD: 10 Yrs",
    selection_process: "Computer Based Examination (Session-I & Session-II), PST/PET for Havaldar, Document Verification",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹100",
    application_fee_general: "₹100",
    application_fee_ews: "₹100",
    application_fee_female: "₹0",
    application_fee_pwd: "₹0",
    application_fee_other: "Women and SC/ST/PwD/ESM: ₹0/-",
    notification_date: daysAgo(10),
    start_date: daysAgo(8),
    last_date: daysAhead(28), // OPEN
    exam_date: daysAhead(70),
    admit_card_date: daysAhead(60),
    result_date: null,
    official_website: "https://ssc.gov.in",
    official_notification_url: "https://ssc.gov.in/notice-modal/CHSL_2026_Notice.pdf",
    application_url: "https://ssc.gov.in/portal/login",
    job_description: "SSC CHSL (Combined Higher Secondary Level 10+2) Examination 2026 for recruitment to Lower Division Clerk (LDC), Junior Secretariat Assistant (JSA), and Data Entry Operator (DEO) in various Central Government Ministries and Offices.",
    eligibility: "Candidates must have passed 12th Standard or equivalent examination from a recognized Board or University. For DEO in CAG office: 12th Standard pass in Science stream with Mathematics as a subject.",
    required_documents: "1. 10th and 12th Passing Certificates\n2. Live Webcam Photo capture as per SSC norms\n3. Signature scan (10 to 20 KB)\n4. Photo Identity Proof (Aadhaar/Voter ID/PAN)\n5. Category Certificate",
    how_to_apply: "1. Visit the new SSC portal ssc.gov.in\n2. Complete One Time Registration (OTR)\n3. Fill in CHSL application form\n4. Upload live photograph and signature\n5. Pay fee of ₹100 online\n6. Verify details and submit final form",
    official_notification_url: "https://ssc.gov.in/notice_mts_2026.pdf",
    application_url: "https://ssc.gov.in",
    job_description: "Staff Selection Commission (SSC) Multi Tasking (Non-Technical) Staff, and Havaldar (CBIC & CBN) Examination, 2026. General central service Group 'C' non-gazetted, non-ministerial posts.",
    eligibility: "Candidates must have passed Matriculation (10th Standard) Examination or equivalent from a recognized Board.",
    required_documents: "1. 10th Marks card\n2. Live Webcam Photo\n3. Signature\n4. Valid Photo ID proof",
    how_to_apply: "1. Visit ssc.gov.in and login via OTR\n2. Open MTS 2026 form\n3. Choose post preference and state codes\n4. Submit and pay fee online",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "ssc-cgl-recruitment-2026",
    post_name: "Assistant Section Officer, Inspector, Sub-Inspector",
    organization_name: "Staff Selection Commission (SSC)",
    department: "Central Ministries, CBDT, CBIC, CBI, ED",
    slug: "ssc-stenographer-recruitment-2026",
    post_name: "SSC Stenographer Recruitment 2026",
    organization_name: "Staff Selection Commission",
    department: "Various Central Ministries and Subordinate Offices",
    government_field: "SSC",
    government_level: "Central Government",
    state: "All India",
    qualification: "Bachelor's Degree from a recognized University or equivalent",
    qualification_level: "ANY GRADUATE",
    qualification: "12th Pass",
    qualification_level: "12TH",
    qualification_details: "12th Standard or Equivalent from a recognized Board or University",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 17727,
    number_of_posts: 2000,
    salary_min: 25500,
    salary_max: 151100,
    salary_text: "₹25,500 – ₹1,51,100 (Pay Level 4 to 8)",
    salary_max: 81100,
    salary_text: "₹25,500 – ₹81,100",
    age_min: 18,
    age_max: 32,
    age_relaxation: "OBC: 3 Yrs, SC/ST: 5 Yrs, PwD: 10 Yrs",
    selection_process: "Tier-I CBT, Tier-II CBT & Document Verification",
    application_fee_sc_st: "₹0/-",
    application_fee_obc: "₹100/-",
    application_fee_general: "₹100/-",
    application_fee_other: "Women/SC/ST/PwD/ESM: ₹0/-",
    notification_date: new Date("2026-08-20"),
    start_date: new Date("2026-08-25"),
    last_date: new Date("2026-09-24"), // Closing soon!
    exam_date: new Date("2026-10-30"),
    admit_card_date: new Date("2026-10-20"),
    age_max: 27,
    age_relaxation: "SC/ST: 5 Yrs, OBC: 3 Yrs, PwD: 10 Yrs",
    selection_process: "Computer Based Test (CBT - General Intelligence, Reasoning, English), Skill Test in Stenography (Hindi/English)",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹100",
    application_fee_general: "₹100",
    application_fee_ews: "₹100",
    application_fee_female: "₹0",
    application_fee_pwd: "₹0",
    application_fee_other: "Women and SC/ST/PwD: ₹0/-",
    notification_date: daysAgo(2),
    start_date: daysAhead(5), // UPCOMING
    last_date: daysAhead(40),
    exam_date: daysAhead(90),
    admit_card_date: daysAhead(80),
    result_date: null,
    official_website: "https://ssc.gov.in",
    official_notification_url: "https://ssc.gov.in/notice_cgl_2026.pdf",
    official_notification_url: "https://ssc.gov.in/notice_steno_2026.pdf",
    application_url: "https://ssc.gov.in",
    job_description: "Staff Selection Commission Combined Graduate Level (CGL) Examination 2026 for recruitment to Group 'B' and Group 'C' posts in various Ministries/ Departments/ Organizations of the Government of India.",
    eligibility: "Bachelor’s Degree from a recognized University or equivalent. Mathematical statistics required for Junior Statistical Officer (JSO).",
    required_documents: "1. Graduation Degree Certificate\n2. Live Web Camera Photograph\n3. Signature\n4. Valid Photo ID",
    how_to_apply: "1. Login at ssc.gov.in with OTR credentials\n2. Access CGL 2026 Application form\n3. Select Exam Centre & upload photo\n4. Pay application fee and submit",
    job_description: "SSC Stenographer Grade 'C' (Group B Non-Gazetted) and Grade 'D' (Group C) Examination 2026 for Ministries, Departments, and Subordinate offices across India.",
    eligibility: "Candidates must have passed 12th standard or equivalent from a recognized board. Must pass stenography dictation (80 wpm for Gr D, 100 wpm for Gr C) and transcription test.",
    required_documents: "1. 12th Standard Certificate\n2. Live Photo\n3. Signature\n4. ID Proof",
    how_to_apply: "1. Register/Login at ssc.gov.in\n2. Submit online application once window opens\n3. Select medium of stenography test (Hindi/English)",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "indian-postal-gds-recruitment-2026",
    post_name: "GDS, BPM, ABPM",
    organization_name: "India Post (Department of Posts)",
    department: "Ministry of Communications",
    government_field: "Postal",
    government_level: "Central Government",
    state: "All India",
    qualification: "10th Pass with Computer Knowledge & Local Language",
    qualification_level: "10TH",
    qualification_details: "10th standard pass certificate with mathematics and English",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 23757,
    salary_min: 10000,
    salary_max: 30000,
    salary_text: "₹10,000 – ₹30,000 (TRCA Slab)",
    age_min: 18,
    age_max: 40,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 Years",
    selection_process: "Merit List based on Class 10th Marks, No Exam, No Interview",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹100",
    application_fee_general: "₹100",
    application_fee_ews: "₹100",
    application_fee_female: "₹0",
    application_fee_pwd: "₹0",
    application_fee_other: "PwD/Female: ₹0/-",
    notification_date: daysAgo(25),
    start_date: daysAgo(20),
    last_date: daysAhead(1), // Closing soon
    exam_date: null,
    admit_card_date: null,
    result_date: daysAhead(20),
    official_website: "https://www.indiapost.gov.in",
    official_notification_url: "https://indiapostgdsonline.gov.in/Notifications/GDS_Recruitment_2026.pdf",
    application_url: "https://indiapostgdsonline.gov.in",
    job_description: "Department of Posts Gramin Dak Sevaks (GDS), Branch Postmaster (BPM), and Assistant Branch Postmaster (ABPM) recruitment across 23 postal circles nationwide.",
    eligibility: "Secondary School Examination pass certificate of 10th standard with passing marks in Mathematics and English conducted by any recognized Board of School Education.",
    required_documents: "1. 10th Marks Memo/Certificate\n2. Photo (up to 50KB)\n3. Signature (up to 20KB)\n4. Community Certificate",
    how_to_apply: "Apply online at indiapostgdsonline.gov.in.",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "rrb-ntpc-graduate-recruitment-2026",
    post_name: "Station Master, Goods Train Manager, Senior Clerk",
    organization_name: "Railway Recruitment Boards (RRB)",
    department: "Ministry of Railways",
    government_field: "Railway",
    government_level: "Central Government",
    state: "All India",
    qualification: "Any Graduation Degree from recognized University",
    qualification_level: "ANY GRADUATE",
    qualification_details: "Bachelor's Degree in any discipline from a recognized University",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 8113,
    salary_min: 29200,
    salary_max: 92300,
    salary_text: "₹29,200 – ₹92,300 (Pay Level 5 & 6)",
    age_min: 18,
    age_max: 36,
    age_relaxation: "OBC: 3 Years, SC/ST: 5 Years, PwD: 10 Years, 3 Years COVID age relaxation applied",
    selection_process: "1st Stage CBT, 2nd Stage CBT, CBAT (Station Master) / Typing Skill Test, Document Verification & Medical Exam",
    application_fee_sc_st: "₹250/- (Refundable after attending CBT-1)",
    application_fee_obc: "₹500/- (₹400 refundable after attending CBT-1)",
    application_fee_general: "₹500/- (₹400 refundable after attending CBT-1)",
    application_fee_other: "Female, Ex-SM, Transgender, Minorities & EBC: ₹250/-",
    notification_date: new Date("2026-09-12"),
    start_date: new Date("2026-09-14"),
    last_date: new Date("2026-10-13"),
    exam_date: new Date("2026-12-10"),
    admit_card_date: new Date("2026-12-01"),
    age_relaxation: "OBC: 3 Years, SC/ST: 5 Years, PwD: 10 Years",
    selection_process: "1st Stage CBT, 2nd Stage CBT, CBAT / Typing Skill Test, Document Verification & Medical Exam",
    application_fee_sc_st: "₹250 (Refundable)",
    application_fee_obc: "₹500 (₹400 Refundable)",
    application_fee_general: "₹500 (₹400 Refundable)",
    application_fee_ews: "₹500",
    application_fee_female: "₹250",
    application_fee_pwd: "₹250",
    application_fee_other: "Female, Ex-SM: ₹250/-",
    notification_date: daysAgo(12),
    start_date: daysAgo(10),
    last_date: daysAhead(20), // OPEN
    exam_date: daysAhead(75),
    admit_card_date: daysAhead(65),
    result_date: null,
    official_website: "https://www.rrbapply.gov.in",
    official_notification_url: "https://www.rrbapply.gov.in/notices/CEN_06_2026_NTPC_Grad.pdf",
    application_url: "https://www.rrbapply.gov.in",
    job_description: "Railway Recruitment Boards (RRBs) invite online applications from eligible Indian citizens for Non-Technical Popular Categories (Graduate) posts including Station Master, Goods Train Manager, Chief Commercial cum Ticket Supervisor, Senior Clerk cum Typist, Junior Accounts Assistant cum Typist across various Zonal Railways.",
    eligibility: "University Degree from recognized University or its equivalent. Medical standard A-2 for Station Master, A-3 for Goods Train Manager.",
    required_documents: "1. Graduation Degree / Provisional Certificate\n2. Matriculation Certificate for Date of Birth\n3. Caste Certificate in prescribed format\n4. Digital Photo & Signature",
    how_to_apply: "1. Go to rrbapply.gov.in\n2. Create an account with Mobile and Email\n3. Select RRB zone and post preference\n4. Submit educational details and upload documents\n5. Pay examination fee and download receipt",
    job_description: "Non-Technical Popular Categories (Graduate) posts including Station Master, Goods Train Manager, Chief Commercial cum Ticket Supervisor across various Zonal Railways.",
    eligibility: "University Degree from recognized University or its equivalent. Medical standard A-2 for Station Master.",
    required_documents: "1. Graduation Certificate\n2. 10th Certificate for DOB\n3. Caste Certificate\n4. Digital Photo & Signature",
    how_to_apply: "Apply online at rrbapply.gov.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "ibps-rrb-crp-xv-recruitment-2026",
    post_name: "Office Assistant (Multipurpose) & Officer Scale-I",
    organization_name: "Institute of Banking Personnel Selection (IBPS)",
    department: "Regional Rural Banks (Gramin Banks)",
    government_field: "Banking",
    government_level: "Central Government",
    state: "All India",
    qualification: "Bachelor's Degree in any discipline from a recognized University",
    qualification: "Bachelor's Degree in any discipline",
    qualification_level: "ANY GRADUATE",
    qualification_details: "Bachelor's Degree in any discipline from a recognized University or equivalent",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 13706,
    salary_min: 25000,
    salary_max: 55000,
    salary_text: "₹25,000 – ₹55,000 per month (inclusive of allowances)",
    salary_text: "₹25,000 – ₹55,000 per month",
    age_min: 18,
    age_max: 30,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 Years",
    selection_process: "Preliminary Exam, Main Exam, Interview (Scale-I only). No Interview for Office Assistant.",
    application_fee_sc_st: "₹175/- (inclusive of GST)",
    application_fee_obc: "₹850/- (inclusive of GST)",
    application_fee_general: "₹850/- (inclusive of GST)",
    application_fee_other: "PwD: ₹175/-, EWS: ₹850/-",
    notification_date: new Date("2026-08-30"),
    start_date: new Date("2026-09-01"),
    last_date: new Date("2026-09-23"), // Closing tomorrow!
    exam_date: new Date("2026-10-20"),
    admit_card_date: new Date("2026-10-10"),
    application_fee_sc_st: "₹175",
    application_fee_obc: "₹850",
    application_fee_general: "₹850",
    application_fee_ews: "₹850",
    application_fee_female: "₹850",
    application_fee_pwd: "₹175",
    application_fee_other: "SC/ST/PwD: ₹175, All Others: ₹850",
    notification_date: daysAgo(22),
    start_date: daysAgo(20),
    last_date: daysAhead(1), // Closing soon
    exam_date: daysAhead(30),
    admit_card_date: daysAhead(20),
    result_date: null,
    official_website: "https://www.ibps.in",
    official_notification_url: "https://www.ibps.in/crp-rrb-xv/detailed-notification.pdf",
    application_url: "https://ibpsonline.ibps.in/rrbxvjun26/",
    job_description: "The Common Recruitment Process for RRBs (CRP RRBs XV) for recruitment of Group 'A'-Officers (Scale-I, II & III) and Group 'B'-Office Assistants (Multipurpose) in 43 Participating Regional Rural Banks across India.",
    eligibility: "Bachelor's degree in any discipline from a recognized University or its equivalent. Proficiency in local language as prescribed by the participating RRB. Working knowledge of Computer is required.",
    required_documents: "1. Photograph (4.5cm × 3.5cm)\n2. Signature (not in capital letters)\n3. Left thumb impression\n4. Hand written declaration\n5. Graduation marks card",
    how_to_apply: "1. Visit www.ibps.in\n2. Click on CRP RRBs XV\n3. Fill in registration details and generate Provisional Registration Number\n4. Upload Photo, Signature, Left Thumb, Hand Written Declaration\n5. Pay fee online through Debit/Credit card/UPI",
    application_url: "https://ibpsonline.ibps.in",
    job_description: "Common Recruitment Process for RRBs (CRP RRBs XV) for Group 'A'-Officers (Scale-I) and Group 'B'-Office Assistants in 43 Participating Regional Rural Banks across India.",
    eligibility: "Bachelor's degree in any discipline from a recognized University. Proficiency in local language as prescribed by the participating RRB.",
    required_documents: "1. Photograph\n2. Signature\n3. Left thumb impression\n4. Hand written declaration",
    how_to_apply: "Apply online at ibps.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "sbi-po-recruitment-2026",
    post_name: "Probationary Officer (PO)",
    organization_name: "State Bank of India (SBI)",
    department: "Central Recruitment & Promotion Department",
    government_field: "Banking",
    government_level: "Central Government",
    state: "All India",
    qualification: "Graduation in any discipline",
    qualification_level: "ANY GRADUATE",
    qualification_details: "Graduation in any discipline from a recognized University or equivalent",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 2000,
    salary_min: 41960,
    salary_max: 63840,
    salary_text: "₹41,960 – ₹63,840 + DA, HRA, Perks",
    age_min: 21,
    age_max: 30,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 to 15 Years",
    selection_process: "Phase-I (Prelims), Phase-II (Mains + Descriptive Test), Phase-III (Psychometric Test, Group Exercise & Interview)",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹750",
    application_fee_general: "₹750",
    application_fee_ews: "₹750",
    application_fee_female: "₹750",
    application_fee_pwd: "₹0",
    application_fee_other: "SC/ST/PwD: ₹0, General/EWS/OBC: ₹750",
    notification_date: daysAgo(5),
    start_date: daysAhead(3), // UPCOMING
    last_date: daysAhead(32),
    exam_date: daysAhead(65),
    admit_card_date: daysAhead(55),
    result_date: null,
    official_website: "https://sbi.co.in",
    official_notification_url: "https://bank.sbi/careers/PO_2026_Notification.pdf",
    application_url: "https://ibpsonline.ibps.in/sbiposep26/",
    job_description: "State Bank of India recruitment of Probationary Officers (PO) for junior management grade scale-I. Premier banking career opportunity with nation-wide posting.",
    eligibility: "Graduation in any discipline from a recognized University or any equivalent qualification recognized by Central Government. Final year students may also apply.",
    required_documents: "1. Graduation Marksheet\n2. Photo & Signature\n3. Left Thumb & Declaration",
    how_to_apply: "Apply online at sbi.co.in/careers",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "delhi-police-constable-recruitment-2026",
    post_name: "Constable (Executive) Male & Female",
    organization_name: "Staff Selection Commission / Delhi Police",
    department: "Ministry of Home Affairs",
    government_field: "Police",
    government_level: "Central Government",
    state: "Delhi",
    qualification: "10+2 (Senior Secondary) pass with valid LMV Driving License for Male",
    qualification: "10+2 (Senior Secondary) pass with valid LMV License for Male",
    qualification_level: "12TH",
    qualification_details: "10+2 pass from a recognized board with LMV Driving License for Male candidates",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 7547,
    salary_min: 21700,
    salary_max: 69100,
    salary_text: "₹21,700 – ₹69,100 (Pay Level-3)",
    age_min: 18,
    age_max: 25,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, Sports Persons: 5 Years",
    selection_process: "Computer Based Exam (100 Marks), Physical Endurance & Measurement Test (PE&MT), Medical Examination",
    application_fee_sc_st: "₹0/-",
    application_fee_obc: "₹100/-",
    application_fee_general: "₹100/-",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹100",
    application_fee_general: "₹100",
    application_fee_ews: "₹100",
    application_fee_female: "₹0",
    application_fee_pwd: "₹0",
    application_fee_other: "Women and SC/ST/Ex-Servicemen: ₹0/-",
    notification_date: new Date("2026-09-01"),
    start_date: new Date("2026-09-05"),
    last_date: new Date("2026-09-24"), // Closing soon!
    exam_date: new Date("2026-11-20"),
    admit_card_date: new Date("2026-11-10"),
    notification_date: daysAgo(15),
    start_date: daysAgo(10),
    last_date: daysAhead(18), // OPEN
    exam_date: daysAhead(55),
    admit_card_date: daysAhead(45),
    result_date: null,
    official_website: "https://delhipolice.gov.in",
    official_notification_url: "https://ssc.gov.in/delhi-police-constable-2026.pdf",
    application_url: "https://ssc.gov.in",
    job_description: "Recruitment of Constable (Executive) Male and Female in Delhi Police Examination 2026. Opportunities for youth to serve in the capital police force.",
    eligibility: "10+2 (Senior Secondary) pass from a recognized Board. Male candidates must possess a valid driving license for LMV (Motor cycle or Car) as on the date of PE&MT. Learner license is not acceptable.",
    required_documents: "1. 10th & 12th Marksheets\n2. LMV Driving License (for Male)\n3. Photo and Signature\n4. Domicile/Category Certificate",
    how_to_apply: "1. Apply online via SSC portal ssc.gov.in\n2. Fill Delhi Police Constable application form\n3. Upload photo/signature\n4. Pay application fee\n5. Take printout of submitted form",
    job_description: "Recruitment of Constable (Executive) Male and Female in Delhi Police Examination 2026 conducted by Staff Selection Commission.",
    eligibility: "10+2 (Senior Secondary) pass from a recognized Board. Male candidates must possess valid LMV driving license.",
    required_documents: "1. 10th & 12th Marksheets\n2. LMV Driving License\n3. Photo and Signature",
    how_to_apply: "Apply online at ssc.gov.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "upsc-combined-defence-services-cds-2026",
    post_name: "Officers in IMA, INA, AFA, OTA",
    organization_name: "Union Public Service Commission (UPSC)",
    department: "Ministry of Defence",
    government_field: "Defence",
    government_level: "Central Government",
    state: "All India",
    qualification: "Graduation Degree in any discipline / Engineering for Air Force & Navy",
    qualification: "Graduation Degree in any discipline / Engineering",
    qualification_level: "ANY GRADUATE",
    qualification_details: "Degree of a recognized University or Bachelor of Engineering for Technical wings",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 459,
    salary_min: 56100,
    salary_max: 177500,
    salary_text: "₹56,100 – ₹1,77,500 (Level 10 + Military Service Pay ₹15,500)",
    salary_text: "₹56,100 – ₹1,77,500 (Level 10 + MSP)",
    age_min: 19,
    age_max: 24,
    age_relaxation: "As per Defence service rules",
    selection_process: "UPSC Written Examination (English, GK, Elementary Maths), SSB Interview (5 Days), Medical Examination",
    application_fee_sc_st: "₹0/-",
    application_fee_obc: "₹200/-",
    application_fee_general: "₹200/-",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹200",
    application_fee_general: "₹200",
    application_fee_ews: "₹200",
    application_fee_female: "₹0",
    application_fee_pwd: "₹0",
    application_fee_other: "Female/SC/ST: ₹0/- (Exempted)",
    notification_date: new Date("2026-08-10"),
    start_date: new Date("2026-08-15"),
    last_date: new Date("2026-09-26"), // Closing soon!
    exam_date: new Date("2026-11-08"),
    admit_card_date: new Date("2026-10-25"),
    notification_date: daysAgo(20),
    start_date: daysAgo(15),
    last_date: daysAhead(14), // OPEN
    exam_date: daysAhead(50),
    admit_card_date: daysAhead(40),
    result_date: null,
    official_website: "https://upsc.gov.in",
    official_notification_url: "https://upsc.gov.in/sites/default/files/Notice-CDSE-II-2026-engl.pdf",
    application_url: "https://upsconline.nic.in",
    job_description: "Combined Defence Services Examination (II), 2026 for admission to Indian Military Academy (IMA), Indian Naval Academy (INA), Air Force Academy (AFA), and Officers Training Academy (OTA Chennai).",
    eligibility: "For I.M.A. and Officers' Training Academy: Degree of a recognized University. For Indian Naval Academy: Degree in Engineering. For Air Force Academy: Degree of a recognized University (with Physics and Mathematics at 10+2 level) or Bachelor of Engineering.",
    required_documents: "1. UPSC OTR Profile\n2. Scanned Photo and Signature\n3. Valid Govt Photo ID (Aadhaar/Passport/Driving License)\n4. Graduation Degree Certificate",
    how_to_apply: "1. Visit upsconline.nic.in and log in with OTR\n2. Fill CDS Part-I and Part-II registration\n3. Select Exam Centre\n4. Pay application fee\n5. Submit application and save receipt",
    eligibility: "For I.M.A. and OTA: Degree of a recognized University. For INA: Degree in Engineering. For AFA: Degree with Physics & Math at 10+2 level or B.E.",
    required_documents: "1. UPSC OTR Profile\n2. Photo & Signature\n3. Photo ID Proof\n4. Degree Certificate",
    how_to_apply: "Apply online at upsconline.nic.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "ssc-junior-engineer-je-2026",
    post_name: "Junior Engineer (Civil, Electrical, Mechanical)",
    organization_name: "Staff Selection Commission (SSC)",
    department: "Central Public Works Department (CPWD) & MES",
    government_field: "Engineering",
    government_level: "Central Government",
    state: "All India",
    qualification: "Degree or Diploma in Civil / Electrical / Mechanical Engineering",
    qualification: "Degree or Diploma in Engineering (Civil/Mech/Elec)",
    qualification_level: "ENGINEERING",
    qualification_details: "Degree or 3-year Diploma in Civil, Electrical, or Mechanical Engineering from a recognized Institute",
    specific_discipline: "Civil, Electrical, Mechanical",
    exact_qual_required: true,
    number_of_posts: 1748,
    salary_min: 35400,
    salary_max: 112400,
    salary_text: "₹35,400 – ₹1,12,400 (Pay Level 6)",
    age_min: 18,
    age_max: 30,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 Years",
    selection_process: "Paper-I (CBT Objective 200 Marks), Paper-II (CBT Technical 300 Marks), Document Verification",
    application_fee_sc_st: "₹0/-",
    application_fee_obc: "₹100/-",
    application_fee_general: "₹100/-",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹100",
    application_fee_general: "₹100",
    application_fee_ews: "₹100",
    application_fee_female: "₹0",
    application_fee_pwd: "₹0",
    application_fee_other: "Women and SC/ST/PwD/ESM: ₹0/-",
    notification_date: new Date("2026-09-05"),
    start_date: new Date("2026-09-10"),
    last_date: new Date("2026-10-08"),
    exam_date: new Date("2026-12-05"),
    admit_card_date: new Date("2026-11-25"),
    notification_date: daysAgo(10),
    start_date: daysAgo(5),
    last_date: daysAhead(22), // OPEN
    exam_date: daysAhead(70),
    admit_card_date: daysAhead(60),
    result_date: null,
    official_website: "https://ssc.gov.in",
    official_notification_url: "https://ssc.gov.in/notice_je_2026.pdf",
    application_url: "https://ssc.gov.in",
    job_description: "Staff Selection Commission Junior Engineer Examination 2026 for Group 'B' Non-Gazetted posts in CPWD, Military Engineer Services (MES), Central Water Commission (CWC), and Border Roads Organization (BRO).",
    eligibility: "Degree or 3-year Diploma in Civil, Electrical, or Mechanical Engineering from a recognized University/Institute. (For Diploma holders, 2 years experience required in some organizations).",
    required_documents: "1. Engineering Degree/Diploma certificate\n2. Experience certificate (if applicable)\n3. Live Photo & Signature\n4. Caste Certificate",
    how_to_apply: "1. Apply online at ssc.gov.in\n2. Select Engineering discipline\n3. Fill educational marks and post preferences\n4. Pay application fee and submit",
    job_description: "Junior Engineer Examination 2026 for Group 'B' Non-Gazetted posts in CPWD, Military Engineer Services (MES), and Border Roads Organization (BRO).",
    eligibility: "Degree or 3-year Diploma in Civil, Electrical, or Mechanical Engineering from recognized University/Board.",
    required_documents: "1. Engineering Degree/Diploma certificate\n2. Photo & Signature\n3. Caste Certificate",
    how_to_apply: "Apply online at ssc.gov.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "karnataka-teacher-recruitment-2026",
    post_name: "Graduate Primary Teacher (Class 6-8)",
    organization_name: "Department of Public Instruction, Karnataka",
    department: "School Education Department",
    government_field: "Teaching",
    government_level: "State Government",
    state: "Karnataka",
    qualification: "Graduation (BA/B.Sc) with B.Ed / D.El.Ed and KARTET / CTET Paper-II",
    qualification: "Graduation (BA/B.Sc) with B.Ed / D.El.Ed and TET",
    qualification_level: "ANY GRADUATE",
    qualification_details: "Bachelor's Degree in Science/Arts with at least 50% marks, B.Ed and qualified in KARTET/CTET Paper-II",
    specific_discipline: "Social Science, Mathematics & Science, English",
    exact_qual_required: false,
    number_of_posts: 15000,
    salary_min: 27650,
    salary_max: 52650,
    salary_text: "₹27,650 – ₹52,650 (State Pay Scale)",
    age_min: 21,
    age_max: 42,
    age_relaxation: "2A/2B/3A/3B: 3 Years, SC/ST/Cat-I: 5 Years, PwD: 10 Years",
    selection_process: "Competitive Written Exam (Paper-I, II, III), KARTET Weightage, Document Verification",
    application_fee_sc_st: "₹500/-",
    application_fee_obc: "₹1,000/-",
    application_fee_general: "₹1,000/-",
    application_fee_sc_st: "₹500",
    application_fee_obc: "₹1000",
    application_fee_general: "₹1000",
    application_fee_ews: "₹1000",
    application_fee_female: "₹1000",
    application_fee_pwd: "₹0",
    application_fee_other: "Cat-I: ₹500/-, PwD: Exempted",
    notification_date: new Date("2026-08-25"),
    start_date: new Date("2026-09-01"),
    last_date: new Date("2026-09-25"), // Closing soon!
    exam_date: new Date("2026-11-28"),
    admit_card_date: new Date("2026-11-15"),
    notification_date: daysAgo(25),
    start_date: daysAgo(20),
    last_date: daysAhead(10), // OPEN
    exam_date: daysAhead(45),
    admit_card_date: daysAhead(35),
    result_date: null,
    official_website: "https://schooleducation.karnataka.gov.in",
    official_notification_url: "https://schooleducation.karnataka.gov.in/notices/Teacher_Recruitment_15000.pdf",
    application_url: "https://schooleducation.karnataka.gov.in/recruitment",
    job_description: "Government of Karnataka recruitment for 15,000 Graduate Primary Teachers in Government Model Primary Schools (Classes 6-8) across various districts of Karnataka.",
    eligibility: "Bachelor's Degree in Science/Arts with at least 50% marks, B.Ed or 2-year D.El.Ed, and qualified in KARTET Paper-II or CTET Paper-II.",
    required_documents: "1. Degree and B.Ed/D.El.Ed Marks cards\n2. KARTET/CTET Scorecard\n3. Kannada Medium & Rural Study Certificate (if claiming quota)\n4. Caste and Income Certificate",
    how_to_apply: "1. Visit schooleducation.karnataka.gov.in\n2. Fill online teacher application form\n3. Enter district and subject preferences\n4. Pay application fee through SBI Collect\n5. Submit and take printout",
    job_description: "Recruitment of 15,000 Graduate Primary Teachers in Government Model Primary Schools across Karnataka.",
    eligibility: "Bachelor's Degree in Science/Arts with at least 50% marks, B.Ed or D.El.Ed, and qualified in KARTET Paper-II or CTET Paper-II.",
    required_documents: "1. Degree & B.Ed Marks cards\n2. KARTET/CTET Scorecard\n3. Kannada Medium & Domicile proof",
    how_to_apply: "Apply online at schooleducation.karnataka.gov.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "pgimer-nursing-officer-recruitment-2026",
    post_name: "Nursing Officer Grade-II",
    organization_name: "PGIMER Chandigarh",
    department: "Ministry of Health and Family Welfare",
    government_field: "Healthcare",
    government_level: "Central Government",
    state: "All India",
    qualification: "B.Sc (Hons) Nursing / B.Sc Nursing or GNM with 2 Yrs Experience",
    qualification: "B.Sc (Hons) Nursing / B.Sc Nursing or GNM with 2 Yrs Exp",
    qualification_level: "NURSING",
    qualification_details: "B.Sc. Nursing from Indian Nursing Council recognized Institute OR Diploma in GNM with 2 years experience",
    specific_discipline: "Nursing",
    exact_qual_required: true,
    number_of_posts: 243,
    salary_min: 44900,
    salary_max: 142400,
    salary_text: "₹44,900 – ₹1,42,400 (Pay Level-7)",
    age_min: 18,
    age_max: 35,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 Years",
    selection_process: "Online Computer Based Test (CBT - 100 MCQs), Document Verification",
    application_fee_sc_st: "₹800/-",
    application_fee_obc: "₹1,500/-",
    application_fee_general: "₹1,500/-",
    application_fee_sc_st: "₹800",
    application_fee_obc: "₹1500",
    application_fee_general: "₹1500",
    application_fee_ews: "₹1500",
    application_fee_female: "₹1500",
    application_fee_pwd: "₹0",
    application_fee_other: "EWS: ₹1,500/-, PwD: ₹0/- (Exempted)",
    notification_date: new Date("2026-09-02"),
    start_date: new Date("2026-09-08"),
    last_date: new Date("2026-09-28"),
    exam_date: new Date("2026-11-12"),
    admit_card_date: new Date("2026-11-01"),
    notification_date: daysAgo(18),
    start_date: daysAgo(12),
    last_date: daysAhead(12), // OPEN
    exam_date: daysAhead(50),
    admit_card_date: daysAhead(40),
    result_date: null,
    official_website: "https://pgimer.edu.in",
    official_notification_url: "https://pgimer.edu.in/pdf/Nursing_Officer_Advt_2026.pdf",
    application_url: "https://pgimer.edu.in/recruitments",
    job_description: "Postgraduate Institute of Medical Education & Research (PGIMER), Chandigarh invites applications for direct recruitment of Nursing Officer Grade-II on regular basis.",
    eligibility: "B.Sc. (Hons.) Nursing / B.Sc. Nursing from an Indian Nursing Council recognized Institute OR Diploma in General Nursing and Midwifery (GNM) with two years experience in a minimum 50 bedded Hospital. Registered as Nurse & Midwife with State/Indian Nursing Council.",
    required_documents: "1. Nursing Degree/Diploma Certificate\n2. Nursing Council Registration Certificate\n3. Experience Certificate (for GNM)\n4. Photo, Signature & Category Proof",
    how_to_apply: "1. Visit pgimer.edu.in\n2. Click on Recruitment section\n3. Register and fill application\n4. Pay application fee online\n5. Save acknowledgement slip",
    job_description: "Postgraduate Institute of Medical Education & Research (PGIMER), Chandigarh direct recruitment of Nursing Officer Grade-II.",
    eligibility: "B.Sc. Nursing from recognized Institute OR Diploma in GNM with 2 years hospital experience. Registered as Nurse & Midwife with Nursing Council.",
    required_documents: "1. Nursing Degree/Diploma Certificate\n2. Registration Certificate\n3. Photo, Signature & Category Proof",
    how_to_apply: "Apply online at pgimer.edu.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "rajasthan-safai-karmachari-recruitment-2026",
    post_name: "Safai Karmachari",
    organization_name: "Department of Local Self Government (DLB), Rajasthan",
    department: "Urban Local Bodies (Nagar Nigam / Nagar Parishad)",
    government_field: "Municipal Government",
    government_level: "Local Government",
    state: "Rajasthan",
    qualification: "8th Class Pass with 1 Year Practical Cleaning Experience in Govt/Private Institution",
    qualification: "8th Class Pass with 1 Year Practical Cleaning Experience",
    qualification_level: "8TH",
    qualification_details: "Minimum 8th class pass and minimum 1 year practical cleaning experience in govt or private body",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 24752,
    salary_min: 17700,
    salary_max: 56200,
    salary_text: "₹17,700 – ₹56,200 (Pay Matrix Level-1)",
    age_min: 18,
    age_max: 40,
    age_relaxation: "SC/ST/OBC/MBC/EWS Male of Rajasthan: 5 Years, Women: 10 Years",
    selection_process: "Scrutiny of applications, Practical Cleaning Skill Test, Document Verification",
    application_fee_sc_st: "₹400/-",
    application_fee_obc: "₹600/-",
    application_fee_general: "₹600/-",
    application_fee_sc_st: "₹400",
    application_fee_obc: "₹600",
    application_fee_general: "₹600",
    application_fee_ews: "₹400",
    application_fee_female: "₹400",
    application_fee_pwd: "₹400",
    application_fee_other: "Disabled/PwD: ₹400/-, Non-Creamy OBC: ₹400/-",
    notification_date: new Date("2026-08-20"),
    start_date: new Date("2026-09-01"),
    last_date: new Date("2026-09-29"),
    notification_date: daysAgo(25),
    start_date: daysAgo(20),
    last_date: daysAhead(15), // OPEN
    exam_date: null,
    admit_card_date: null,
    result_date: null,
    official_website: "https://lsg.urban.rajasthan.gov.in",
    official_notification_url: "https://recruitment.rajasthan.gov.in/safai_advt_2026.pdf",
    application_url: "https://sso.rajasthan.gov.in",
    job_description: "Recruitment of 24,752 Safai Karmacharis across 186 Urban Local Bodies (Municipal Corporations, Councils, Boards) in Rajasthan.",
    eligibility: "Candidate must be a bonafide resident of Rajasthan. Minimum 8th class pass and minimum 1 year practical cleaning experience in state or central government offices, local bodies, contractors, schools, or hospitals.",
    required_documents: "1. 8th Pass Marksheet\n2. Work Experience Certificate\n3. Rajasthan Mool Niwas (Domicile) Certificate\n4. Jan Aadhaar Card\n5. Character Certificate",
    how_to_apply: "1. Login via SSO Rajasthan portal (sso.rajasthan.gov.in)\n2. Access Recruitment Portal\n3. Fill Safai Karmachari form for selected municipality\n4. Pay One Time Registration (OTR) fee\n5. Submit application",
    eligibility: "Candidate must be a bonafide resident of Rajasthan. Minimum 8th class pass and 1 year practical cleaning experience.",
    required_documents: "1. 8th Pass Marksheet\n2. Work Experience Certificate\n3. Rajasthan Domicile Certificate\n4. Jan Aadhaar Card",
    how_to_apply: "Apply via SSO Rajasthan portal (sso.rajasthan.gov.in)",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "upsssc-iti-instructor-recruitment-2026",
    post_name: "Anudeshak (ITI Instructor) Various Trades",
    organization_name: "Uttar Pradesh Subordinate Services Selection Commission (UPSSSC)",
    organization_name: "UPSSSC",
    department: "Vocational Education & Skill Development",
    government_field: "State PSC",
    government_level: "State Government",
    state: "Uttar Pradesh",
    qualification: "High School (10th) with ITI in relevant trade or Diploma/Degree with CITS Certificate",
    qualification: "10th with ITI in relevant trade or Diploma/Degree with CITS",
    qualification_level: "ITI",
    qualification_details: "High School pass, National Craft Instructor Certificate (CITS/NCIC) in relevant trade, and ITI (NTC)",
    specific_discipline: "Electrician, Fitter, Welder, COPA, Turner, Machinist",
    exact_qual_required: true,
    number_of_posts: 2504,
    salary_min: 35400,
    salary_max: 112400,
    salary_text: "₹35,400 – ₹1,12,400 (Pay Scale 9300-34800 Grade Pay 4200)",
    salary_text: "₹35,400 – ₹1,12,400 (GP 4200)",
    age_min: 21,
    age_max: 40,
    age_relaxation: "SC/ST/OBC of UP: 5 Years, Ex-Servicemen: 3 Years",
    selection_process: "Mains Written Examination (for UP PET 2025 short-listed candidates), CITS Marks Weightage",
    application_fee_sc_st: "₹25/-",
    application_fee_obc: "₹25/-",
    application_fee_general: "₹25/-",
    selection_process: "Mains Written Examination (for UP PET short-listed candidates), CITS Marks Weightage",
    application_fee_sc_st: "₹25",
    application_fee_obc: "₹25",
    application_fee_general: "₹25",
    application_fee_ews: "₹25",
    application_fee_female: "₹25",
    application_fee_pwd: "₹25",
    application_fee_other: "All categories processing fee: ₹25/-",
    notification_date: new Date("2026-09-08"),
    start_date: new Date("2026-09-12"),
    last_date: new Date("2026-10-15"),
    exam_date: new Date("2026-12-20"),
    notification_date: daysAgo(14),
    start_date: daysAgo(10),
    last_date: daysAhead(18), // OPEN
    exam_date: daysAhead(60),
    admit_card_date: null,
    result_date: null,
    official_website: "https://upsssc.gov.in",
    official_notification_url: "https://upsssc.gov.in/Open_PDF.aspx?I1=Instructor_2026.pdf",
    application_url: "https://upsssc.gov.in",
    job_description: "UPSSSC recruitment of 2,504 ITI Instructors (Anudeshak) in Industrial Training Institutes across Uttar Pradesh under Vocational Education Department.",
    eligibility: "High School pass, National Craft Instructor Certificate (CITS/NCIC) in relevant trade, and National Trade Certificate (NTC) / ITI with industry/teaching experience.",
    required_documents: "1. UP PET 2025 Registration Number\n2. 10th & ITI Certificates\n3. CITS / Craft Instructor Certificate\n4. Trade Experience Certificate",
    how_to_apply: "1. Login with PET 2025 details on upsssc.gov.in\n2. Verify personal details\n3. Enter ITI and CITS qualifications\n4. Pay ₹25 online fee and submit form",
    job_description: "UPSSSC recruitment of 2,504 ITI Instructors (Anudeshak) in Industrial Training Institutes across Uttar Pradesh.",
    eligibility: "High School pass, National Craft Instructor Certificate (CITS/NCIC) in relevant trade, and ITI with trade experience.",
    required_documents: "1. UP PET Registration Number\n2. 10th & ITI Certificates\n3. CITS Certificate",
    how_to_apply: "Apply online at upsssc.gov.in",
    status: "PUBLISHED",
    is_published: true,
  },
  {
    slug: "rrb-group-d-recruitment-2026",
    post_name: "Track Maintainer, Pointsman, Assistant Workshop",
    organization_name: "Railway Recruitment Boards (RRB)",
    department: "Ministry of Railways",
    government_field: "Railway",
    government_level: "Central Government",
    state: "All India",
    qualification: "10th Pass (Matriculation) or ITI from institutions recognized by NCVT/SCVT",
    qualification_level: "10TH",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 45000,
    salary_min: 18000,
    salary_max: 56900,
    salary_text: "₹18,000 – ₹56,900 (7th CPC Level-1)",
    age_min: 18,
    age_max: 33,
    age_relaxation: "OBC: 3 Years, SC/ST: 5 Years, PwD: 10 Years",
    selection_process: "Computer Based Test (CBT), Physical Efficiency Test (PET), Document Verification & Medical Exam",
    application_fee_sc_st: "₹250/-",
    application_fee_obc: "₹500/-",
    application_fee_general: "₹500/-",
    application_fee_other: "Women, Ex-SM, Transgender, Minorities & EBC: ₹250/-",
    notification_date: new Date("2026-09-18"),
    start_date: new Date("2026-10-01"), // Upcoming Job!
    last_date: new Date("2026-10-31"),
    exam_date: new Date("2027-01-15"),
    admit_card_date: null,
    result_date: null,
    official_website: "https://indianrailways.gov.in",
    official_notification_url: "https://www.rrbapply.gov.in/CEN_07_2026_GroupD_ShortNotice.pdf",
    application_url: "https://www.rrbapply.gov.in",
    job_description: "Advance Notification: Railway Recruitment Cell (RRC/RRB) Centralized Employment Notice for Level-1 Posts (formerly Group D) comprising Track Maintainer Grade-IV, Pointsman, Assistant Loco Shed, Assistant Operations across 16 Zonal Railways.",
    eligibility: "10th pass from recognized board OR National Apprenticeship Certificate (NAC) granted by NCVT OR 10th pass plus ITI.",
    required_documents: "1. 10th Standard Certificate\n2. ITI / NAC Certificate (if applicable)\n3. Digital Photo & Signature\n4. Caste / EWS Certificate",
    how_to_apply: "1. Visit rrbapply.gov.in starting from 01/10/2026\n2. Register and complete user profile\n3. Fill in zone choices and personal data\n4. Pay examination fee and download submission slip",
    status: "PUBLISHED",
  },
  {
    slug: "sbi-po-recruitment-2026",
    post_name: "Probationary Officer (PO)",
    organization_name: "State Bank of India (SBI)",
    department: "Central Recruitment & Promotion Department",
    government_field: "Banking",
    government_level: "Central Government",
    state: "All India",
    qualification: "Graduation in any discipline from a recognized University",
    qualification_level: "ANY GRADUATE",
    specific_discipline: null,
    exact_qual_required: false,
    number_of_posts: 2000,
    salary_min: 41960,
    salary_max: 63840,
    salary_text: "₹41,960 – ₹63,840 + DA, CCA, Leased Accommodation (CTC ~ ₹18 Lakhs/yr)",
    age_min: 21,
    age_max: 30,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 to 15 Years",
    selection_process: "Phase-I (Prelims Exam), Phase-II (Mains Exam + Descriptive Test), Phase-III (Psychometric Test, Group Exercise & Interview)",
    application_fee_sc_st: "₹0/- (Exempted)",
    application_fee_obc: "₹750/-",
    application_fee_general: "₹750/-",
    application_fee_other: "EWS: ₹750/-, SC/ST/PwD: ₹0/-",
    notification_date: new Date("2026-09-19"),
    start_date: new Date("2026-09-28"), // Upcoming Job!
    last_date: new Date("2026-10-25"),
    exam_date: new Date("2026-11-30"),
    admit_card_date: new Date("2026-11-20"),
    result_date: null,
    official_website: "https://sbi.co.in",
    official_notification_url: "https://bank.sbi/careers/PO_2026_Notification.pdf",
    application_url: "https://ibpsonline.ibps.in/sbiposep26/",
    job_description: "State Bank of India recruitment of Probationary Officers (PO) for junior management grade scale-I. One of India's premier banking career opportunities offering fast-track promotions.",
    eligibility: "Graduation in any discipline from a recognized University or any equivalent qualification recognized as such by the Central Government. Those who are in the Final Year/Semester of their Graduation may also apply provisionally.",
    required_documents: "1. Graduation Marksheet/Degree\n2. Recent Passport size Photo\n3. Signature\n4. Left Thumb Impression & Handwritten Declaration",
    how_to_apply: "1. Visit sbi.co.in/careers\n2. Click on 'Recruitment of Probationary Officers'\n3. Register and complete online form\n4. Upload mandatory digital documents\n5. Pay fee of ₹750 online and save receipt",
    status: "PUBLISHED",
  },
  {
    slug: "drdo-ceptam-senior-technical-assistant-2026",
    post_name: "Senior Technical Assistant-B (STA-B)",
    organization_name: "Defence Research & Development Organisation (DRDO)",
    department: "Centre for Personnel Talent Management (CEPTAM)",
    government_field: "Defence",
    government_level: "Central Government",
    state: "All India",
    qualification: "B.Sc Degree in relevant subject or 3 Years Diploma in Engineering/Technology",
    qualification: "3 Years Diploma in Engineering / Technology or B.Sc Degree",
    qualification_level: "DIPLOMA",
    qualification_details: "3 years Diploma in Engineering / Technology or B.Sc. degree in specified subject from recognized University/Board",
    specific_discipline: "Computer Science, Electronics, Mechanical, Electrical, Chemistry, Physics",
    exact_qual_required: false,
    number_of_posts: 1075,
    salary_min: 35400,
    salary_max: 112400,
    salary_text: "₹35,400 – ₹1,12,400 (Pay Level-6)",
    age_min: 18,
    age_max: 28,
    age_relaxation: "SC/ST: 5 Years, OBC: 3 Years, PwD: 10 Years",
    selection_process: "Tier-I (CBT Screening), Tier-II (CBT Technical Test for Selection), Document Verification",
    application_fee_sc_st: "₹0/-",
    application_fee_obc: "₹100/-",
    application_fee_general: "₹100/-",
    application_fee_sc_st: "₹0",
    application_fee_obc: "₹100",
    application_fee_general: "₹100",
    application_fee_ews: "₹100",
    application_fee_female: "₹0",
    application_fee_pwd: "₹0",
    application_fee_other: "Women and SC/ST/PwD/ESM: ₹0/-",
    notification_date: new Date("2026-08-20"),
    start_date: new Date("2026-08-25"),
    last_date: new Date("2026-09-27"), // Closing soon!
    exam_date: new Date("2026-11-10"),
    notification_date: daysAgo(24),
    start_date: daysAgo(18),
    last_date: daysAhead(14), // OPEN
    exam_date: daysAhead(55),
    admit_card_date: null,
    result_date: null,
    official_website: "https://www.drdo.gov.in",
    official_notification_url: "https://www.drdo.gov.in/ceptam-sta-b-2026.pdf",
    application_url: "https://drdo.gov.in/careers",
    job_description: "DRDO CEPTAM invites online applications for Senior Technical Assistant-B (STA-B) in various DRDO laboratories nationwide.",
    eligibility: "3 years Diploma in Engineering / Technology or B.Sc. degree in specified subject from recognized University/Board.",
    job_description: "DRDO CEPTAM online applications for Senior Technical Assistant-B (STA-B) in premier DRDO research establishments nationwide.",
    eligibility: "3 years Diploma in Engineering/Technology or B.Sc. degree in specified subject from recognized University/Board.",
    required_documents: "1. Diploma/B.Sc Certificate\n2. Photo & Signature\n3. Category Certificate",
    how_to_apply: "1. Visit drdo.gov.in and open CEPTAM-11\n2. Register and submit application\n3. Pay ₹100 online and download submission page",
    how_to_apply: "Apply online at drdo.gov.in via CEPTAM portal",
    status: "PUBLISHED",
    is_published: true,
  }
];

async function main() {
  console.log("Seeding Government Jobs...");
  console.log("Seeding GovSearch Government Jobs dataset (DEMO DATA)...");
  for (const job of sampleJobs) {
    await prisma.governmentJob.upsert({
      where: { slug: job.slug },
      update: job,
      create: job,
    });
  }
  console.log(`Successfully seeded ${sampleJobs.length} realistic recruitment records!`);
  console.log(`Successfully seeded ${sampleJobs.length} realistic recruitment records for GovSearch!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
