export interface EducationVacancyItem {
  id: string;
  education: string;
  vacancies: string;
  vacanciesCount: number;
  label: string;
  freeJobAlertUrl: string;
  slug: string;
  level: "School / Matric" | "Certificate / Diploma" | "Graduate / Degree" | "Post Graduate";
  popularExams: string[];
  iconName: string;
  badgeColor: string;
}

export const EDUCATION_VACANCIES_DATA: EducationVacancyItem[] = [
  {
    id: "10TH",
    education: "10TH",
    vacancies: "23,426 Vacancies",
    vacanciesCount: 23426,
    label: "10TH Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/10th-pass-government-jobs/",
    slug: "10th",
    level: "School / Matric",
    popularExams: ["SSC MTS", "Railway Group D", "Post Office GDS", "Police Constable"],
    iconName: "BookOpen",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    id: "8TH",
    education: "8TH",
    vacancies: "11,162 Vacancies",
    vacanciesCount: 11162,
    label: "8TH Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/8th-pass-government-jobs/",
    slug: "8th",
    level: "School / Matric",
    popularExams: ["Peon / Attendant", "High Court Helper", "Forest Watcher", "Driver"],
    iconName: "School",
    badgeColor: "bg-blue-50 text-blue-700 border-blue-200",
  },
  {
    id: "12TH",
    education: "12TH",
    vacancies: "16,438 Vacancies",
    vacanciesCount: 16438,
    label: "12TH Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/12th-pass-government-jobs/",
    slug: "12th",
    level: "School / Matric",
    popularExams: ["SSC CHSL", "NDA", "Indian Army Clerk", "RRB ALP & Technician", "Forest Guard"],
    iconName: "Book",
    badgeColor: "bg-rose-50 text-rose-700 border-rose-200",
  },
  {
    id: "DIPLOMA",
    education: "Diploma",
    vacancies: "10,215 Vacancies",
    vacanciesCount: 10215,
    label: "Diploma Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/diploma-government-jobs/",
    slug: "diploma",
    level: "Certificate / Diploma",
    popularExams: ["SSC JE", "RRB JE", "State PWD JE", "DRDO Technical Asst", "ISRO Technician"],
    iconName: "FileText",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "ITI",
    education: "ITI",
    vacancies: "6,467 Vacancies",
    vacanciesCount: 6467,
    label: "ITI Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/iti-government-jobs/",
    slug: "iti",
    level: "Certificate / Diploma",
    popularExams: ["RRB ALP", "Ordnance Factory", "BHEL Apprentice", "DRDO Trade", "Electricity Board"],
    iconName: "Wrench",
    badgeColor: "bg-purple-50 text-purple-700 border-purple-200",
  },
  {
    id: "B.TECH/B.E",
    education: "B.Tech/B.E",
    vacancies: "5,866 Vacancies",
    vacanciesCount: 5866,
    label: "B.Tech/B.E Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/btech-be-government-jobs/",
    slug: "btech",
    level: "Graduate / Degree",
    popularExams: ["UPSC ESE / IES", "GATE PSU (IOCL, NTPC, ONGC)", "ISRO Scientist", "State AE"],
    iconName: "Settings",
    badgeColor: "bg-sky-50 text-sky-700 border-sky-200",
  },
  {
    id: "B.COM",
    education: "B.com",
    vacancies: "822 Vacancies",
    vacanciesCount: 822,
    label: "B.com Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/bcom-government-jobs/",
    slug: "bcom",
    level: "Graduate / Degree",
    popularExams: ["SSC CGL (AAO)", "RBI Grade B", "Bank Clerk / Accountant", "EPFO SSA"],
    iconName: "BarChart3",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    id: "MBA",
    education: "MBA",
    vacancies: "1,501 Vacancies",
    vacanciesCount: 1501,
    label: "MBA Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/mba-pgdm-government-jobs/",
    slug: "mba",
    level: "Post Graduate",
    popularExams: ["IBPS SO (Marketing / HR)", "SEBI Grade A", "PSU Management Trainee", "NABARD Officer"],
    iconName: "GraduationCap",
    badgeColor: "bg-purple-50 text-purple-700 border-purple-200",
  },
  {
    id: "MSW",
    education: "MSW",
    vacancies: "140 Vacancies",
    vacanciesCount: 140,
    label: "MSW Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/msw-government-jobs/",
    slug: "msw",
    level: "Post Graduate",
    popularExams: ["Women & Child Development", "State Social Welfare Officer", "Rural Livelihood Mission"],
    iconName: "Users",
    badgeColor: "bg-blue-50 text-blue-700 border-blue-200",
  },
  {
    id: "B.SC",
    education: "B.sc",
    vacancies: "6,926 Vacancies",
    vacanciesCount: 6926,
    label: "B.sc Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/bsc-government-jobs/",
    slug: "bsc",
    level: "Graduate / Degree",
    popularExams: ["SSC CGL (JSO / Statistical)", "FCI Assistant", "AFO Agri Officer", "Forensic Lab Tech"],
    iconName: "FlaskConical",
    badgeColor: "bg-cyan-50 text-cyan-700 border-cyan-200",
  },
  {
    id: "M.SC",
    education: "M.sc",
    vacancies: "3,001 Vacancies",
    vacanciesCount: 3001,
    label: "M.sc Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/msc-government-jobs/",
    slug: "msc",
    level: "Post Graduate",
    popularExams: ["CSIR NET JRF", "ISRO / DRDO Junior Scientist", "Geological Survey", "Met Dept"],
    iconName: "FlaskConical",
    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    id: "BA",
    education: "BA",
    vacancies: "706 Vacancies",
    vacanciesCount: 706,
    label: "BA Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/ba-government-jobs/",
    slug: "ba",
    level: "Graduate / Degree",
    popularExams: ["SSC CGL", "State PSC Group 1 & 2", "IBPS Clerk", "UPSC CSE"],
    iconName: "BookOpen",
    badgeColor: "bg-orange-50 text-orange-700 border-orange-200",
  },
  {
    id: "MA",
    education: "MA",
    vacancies: "1,206 Vacancies",
    vacanciesCount: 1206,
    label: "MA Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/ma-government-jobs/",
    slug: "ma",
    level: "Post Graduate",
    popularExams: ["UGC NET Assistant Professor", "PGT School Lecturer", "Archaeological Survey", "Translator"],
    iconName: "Book",
    badgeColor: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "ANY GRADUATE",
    education: "Any Graduate",
    vacancies: "12,884 Vacancies",
    vacanciesCount: 12884,
    label: "Any Graduate Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/any-graduate-government-jobs/",
    slug: "graduate",
    level: "Graduate / Degree",
    popularExams: ["SSC CGL", "IBPS PO / Clerk", "SBI PO", "UPSC CSE", "State Police SI"],
    iconName: "GraduationCap",
    badgeColor: "bg-sky-50 text-sky-700 border-sky-200",
  },
  {
    id: "ANY POST GRADUATE",
    education: "Any Post Graduate",
    vacancies: "1,641 Vacancies",
    vacanciesCount: 1641,
    label: "Any Post Graduate Jobs 2026",
    freeJobAlertUrl: "https://www.freejobalert.com/search-jobs/any-post-graduate-government-jobs/",
    slug: "postgraduate",
    level: "Post Graduate",
    popularExams: ["UPSC Civil Services", "State PSC Group 1", "College Assistant Professor", "RBI Grade B"],
    iconName: "Award",
    badgeColor: "bg-purple-50 text-purple-700 border-purple-200",
  },
];

export const TOTAL_EDUCATION_VACANCIES = EDUCATION_VACANCIES_DATA.reduce(
  (acc, curr) => acc + curr.vacanciesCount,
  0
); // 96,178 Vacancies
