export const QUALIFICATIONS_LIST = [
  "Below 10th",
  "10th / Matriculation",
  "12th / Intermediate",
  "ITI",
  "Diploma",
  "Graduate",
  "ANM",
  "B.A",
  "B.Arch",
  "B.B.A",
  "B.Com",
  "B.Des",
  "B.Ed",
  "B.El.Ed",
  "B.Lib",
  "B.Optom",
  "B.Pharma",
  "B.Plan",
  "B.Sc",
  "B.Tech/B.E",
  "B.Voc",
  "BAMS",
  "BASLP",
  "BBM",
  "BCA",
  "BDS",
  "BFA",
  "BFSc",
  "BHA",
  "BHM",
  "BHMS",
  "BMLT",
  "BOT",
  "BPEd",
  "BPMT",
  "BPT",
  "BSMS",
  "BSW",
  "BUMS",
  "BVA",
  "BVSC",
  "D.El.Ed",
  "D.P.Ed",
  "D.Pharm",
  "DLT",
  "DMLT",
  "DNB",
  "DNB Pathology",
  "GNM",
  "LLB",
  "MBBS",
  "Post Graduate",
  "CA",
  "CS",
  "DM",
  "ICWA",
  "LLM",
  "M.A",
  "M.Arch",
  "M.Ch",
  "M.Com",
  "M.Des",
  "M.E/M.Tech",
  "M.Ed",
  "M.Lib",
  "M.P.Ed",
  "M.Pharma",
  "M.Plan",
  "M.Sc",
  "M.Th",
  "M.Voc",
  "MASLP",
  "Master of Dental Surgery",
  "MBA/PGDM",
  "MCA",
  "MCM",
  "MD Pathology",
  "MFA",
  "MFSc",
  "MHA",
  "MHM",
  "MHS",
  "MLT",
  "MOT",
  "MPA",
  "MPH",
  "MPO",
  "MPT",
  "MS",
  "MS/MD",
  "MSW",
  "MVSC",
  "PG Diploma",
  "PGDBA",
  "PGDBM",
  "PGDCA",
  "PGDMLT",
  "PGP",
  "Doctorate / PhD"
];

export const STATES_AND_CITIES: Record<string, string[]> = {
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati", "Kadapa", "Anantapur", "Other"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Other"],
  "Assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tezpur", "Other"],
  "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Ara", "Other"],
  "Chandigarh": ["Chandigarh"],
  "Chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon", "Other"],
  "Delhi": ["New Delhi", "North Delhi", "South Delhi", "West Delhi", "East Delhi", "Dwarka", "Rohini", "Other"],
  "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Other"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Other"],
  "Haryana": ["Gurugram", "Faridabad", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal", "Other"],
  "Himachal Pradesh": ["Shimla", "Dharamshala", "Mandi", "Solan", "Kullu", "Other"],
  "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur", "Other"],
  "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh", "Other"],
  "Karnataka": ["Bengaluru", "Mysuru", "Hubballi-Dharwad", "Mangaluru", "Belagavi", "Kalaburagi", "Davanagere", "Other"],
  "Kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur", "Kannur", "Other"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Other"],
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Navi Mumbai", "Solapur", "Kolhapur", "Other"],
  "Manipur": ["Imphal", "Churachandpur", "Thoubal", "Other"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Other"],
  "Mizoram": ["Aizawl", "Lunglei", "Champhai", "Other"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Other"],
  "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Other"],
  "Puducherry": ["Puducherry", "Karaikal", "Ozhukarai", "Other"],
  "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Other"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara", "Alwar", "Other"],
  "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Other"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Vellore", "Other"],
  "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar", "Ramagundam", "Other"],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Other"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Varanasi", "Prayagraj", "Agra", "Noida", "Ghaziabad", "Meerut", "Bareilly", "Aligarh", "Gorakhpur", "Other"],
  "Uttarakhand": ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rishikesh", "Nainital", "Other"],
  "West Bengal": ["Kolkata", "Howrah", "Asansol", "Siliguri", "Durgapur", "Bardhaman", "Other"],
  "Andaman and Nicobar Island": ["Port Blair", "Other"],
  "Dadra and Nagar Haveli": ["Silvassa", "Other"],
  "Daman and Diu": ["Daman", "Diu", "Other"],
  "Lakshadweep": ["Kavaratti", "Other"]
};

export const PREFERRED_JOB_CATEGORIES = [
  "Banking",
  "SSC",
  "Railways",
  "UPSC",
  "Defence",
  "Teaching",
  "State PSC",
  "Police",
  "PSU",
  "Govt Engineering"
];

