export interface TodayUpdateItem {
  id: string;
  updateDate: string;
  updateTime: string;
  isToday: boolean;
  category: "Notification" | "Admit Card" | "Exam Date" | "Answer Key" | "Result";
  organization: string;
  boardShort: "SSC" | "UPSC" | "RRB" | "Banking" | "Defence" | "State PSC" | "Police" | "Court";
  postName: string;
  vacancies: string;
  vacanciesCount: number;
  qualification: string;
  lastDateOrExamDate: string;
  statusBadge: string;
  detailsUrl: string;
  applyUrl: string;
  pdfUrl?: string;
  examPatternSlug?: string;
}

export const TODAY_TICKER_ITEMS = [
  {
    id: "ticker-1",
    tag: "BREAKING",
    text: "SSC CGL 2026 Tier-1 Official Provisional Answer Key & Objection Tracker link released today.",
    href: "/mock-tests",
  },
  {
    id: "ticker-2",
    tag: "NEW",
    text: "RRB NTPC 2026 Centralized Employment Notice (11,558 Posts) online applications ongoing.",
    href: "/government-jobs/railway",
  },
  {
    id: "ticker-3",
    tag: "URGENT",
    text: "IBPS PO XIV Mains Exam Call Letters uploaded - Download till exam date.",
    href: "/latest-notifications",
  },
  {
    id: "ticker-4",
    tag: "ADMIT CARD",
    text: "SSC CPO / SI Delhi Police 2026 Paper-1 Application verified; City Intimation Slips starting soon.",
    href: "/dashboard?tab=my_applications",
  },
  {
    id: "ticker-5",
    tag: "LIVE",
    text: "UPSC Civil Services Prelims 2026 detailed subject-wise syllabus & revised exam pattern published.",
    href: "/exam-pattern",
  },
];

export const TODAY_UPDATES_DATA: TodayUpdateItem[] = [
  {
    id: "upd-1",
    updateDate: "29-09-2026",
    updateTime: "11:45 AM",
    isToday: true,
    category: "Notification",
    organization: "Staff Selection Commission (SSC)",
    boardShort: "SSC",
    postName: "Junior Engineer (Civil, Mechanical, Electrical) Exam 2026",
    vacancies: "1,765 Posts",
    vacanciesCount: 1765,
    qualification: "Diploma / B.Tech (Engg)",
    lastDateOrExamDate: "Last Date: 28-10-2026",
    statusBadge: "Active Apply Online",
    detailsUrl: "/job/ssc-je-2026",
    applyUrl: "https://ssc.gov.in/",
    pdfUrl: "https://ssc.gov.in/api/download/ssc_je_2026_notification.pdf",
    examPatternSlug: "ssc-je",
  },
  {
    id: "upd-2",
    updateDate: "29-09-2026",
    updateTime: "11:15 AM",
    isToday: true,
    category: "Notification",
    organization: "Railway Recruitment Boards (RRB)",
    boardShort: "RRB",
    postName: "RRB NTPC Graduate & Under Graduate Posts (CEN 05/2026)",
    vacancies: "11,558 Posts",
    vacanciesCount: 11558,
    qualification: "12th Pass / Any Graduate",
    lastDateOrExamDate: "Last Date: 20-10-2026",
    statusBadge: "Huge Vacancy",
    detailsUrl: "/job/rrb-ntpc-2026",
    applyUrl: "https://www.rrbapply.gov.in/",
    pdfUrl: "https://www.rrbapply.gov.in/documents/CEN_05_2026_NTPC.pdf",
    examPatternSlug: "rrb-ntpc",
  },
  {
    id: "upd-3",
    updateDate: "29-09-2026",
    updateTime: "10:50 AM",
    isToday: true,
    category: "Admit Card",
    organization: "Institute of Banking Personnel Selection (IBPS)",
    boardShort: "Banking",
    postName: "IBPS Probationary Officer (PO/MT XIV) Mains Call Letter 2026",
    vacancies: "3,955 Posts",
    vacanciesCount: 3955,
    qualification: "Any Graduate",
    lastDateOrExamDate: "Exam Date: 12-10-2026",
    statusBadge: "Admit Card Out",
    detailsUrl: "/job/ibps-po-xiv-2026",
    applyUrl: "https://www.ibps.in/",
    pdfUrl: "https://www.ibps.in/call-letter/po-xiv-mains.pdf",
    examPatternSlug: "ibps-po",
  },
  {
    id: "upd-4",
    updateDate: "29-09-2026",
    updateTime: "10:30 AM",
    isToday: true,
    category: "Answer Key",
    organization: "Staff Selection Commission (SSC)",
    boardShort: "SSC",
    postName: "Combined Graduate Level Examination (CGL) 2026 Tier-I Answer Key",
    vacancies: "17,727 Posts",
    vacanciesCount: 17727,
    qualification: "Any Graduate",
    lastDateOrExamDate: "Objections Till: 03-10-2026",
    statusBadge: "Official Key Released",
    detailsUrl: "/mock-tests",
    applyUrl: "https://ssc.gov.in/",
    pdfUrl: "https://ssc.gov.in/api/download/cgl_tier1_key_notice.pdf",
    examPatternSlug: "ssc-cgl",
  },
  {
    id: "upd-5",
    updateDate: "29-09-2026",
    updateTime: "10:05 AM",
    isToday: true,
    category: "Notification",
    organization: "Union Public Service Commission (UPSC)",
    boardShort: "UPSC",
    postName: "Engineering Services Examination (ESE / IES) 2026",
    vacancies: "457 Posts",
    vacanciesCount: 457,
    qualification: "B.E / B.Tech",
    lastDateOrExamDate: "Last Date: 22-10-2026",
    statusBadge: "Gazetted Group A",
    detailsUrl: "/job/upsc-ese-2026",
    applyUrl: "https://upsconline.nic.in/",
    pdfUrl: "https://upsc.gov.in/sites/default/files/Notice-ESE-2026-Engl.pdf",
    examPatternSlug: "upsc-ese",
  },
  {
    id: "upd-6",
    updateDate: "29-09-2026",
    updateTime: "09:40 AM",
    isToday: true,
    category: "Notification",
    organization: "Department of Posts (India Post)",
    boardShort: "State PSC",
    postName: "Gramin Dak Sevaks (GDS) Cycle VI Merit List & Vacancy Expansion",
    vacancies: "21,410 Posts",
    vacanciesCount: 21410,
    qualification: "10th Pass (No Exam)",
    lastDateOrExamDate: "Last Date: 18-10-2026",
    statusBadge: "Direct Merit Based",
    detailsUrl: "/job/india-post-gds-2026",
    applyUrl: "https://indiapostgdsonline.gov.in/",
    pdfUrl: "https://indiapostgdsonline.gov.in/notifications/GDS_2026.pdf",
    examPatternSlug: "india-post-gds",
  },
  {
    id: "upd-7",
    updateDate: "29-09-2026",
    updateTime: "09:15 AM",
    isToday: true,
    category: "Exam Date",
    organization: "Staff Selection Commission (SSC)",
    boardShort: "SSC",
    postName: "Sub-Inspector in Delhi Police & CAPFs (CPO) 2026 Paper-1 CBT Schedule",
    vacancies: "4,187 Posts",
    vacanciesCount: 4187,
    qualification: "Any Graduate",
    lastDateOrExamDate: "Exam: Nov 2026",
    statusBadge: "Schedule Announced",
    detailsUrl: "/dashboard?tab=my_applications",
    applyUrl: "https://ssc.gov.in/",
    pdfUrl: "https://ssc.gov.in/api/download/cpo_2026_exam_notice.pdf",
    examPatternSlug: "ssc-cpo",
  },
  {
    id: "upd-8",
    updateDate: "29-09-2026",
    updateTime: "08:50 AM",
    isToday: true,
    category: "Notification",
    organization: "State Bank of India (SBI)",
    boardShort: "Banking",
    postName: "SBI Specialist Cadre Officers (SCO) Various Trades 2026",
    vacancies: "1,511 Posts",
    vacanciesCount: 1511,
    qualification: "B.Tech / MBA / MCA",
    lastDateOrExamDate: "Last Date: 24-10-2026",
    statusBadge: "Specialist Scale",
    detailsUrl: "/job/sbi-sco-2026",
    applyUrl: "https://sbi.co.in/web/careers",
    pdfUrl: "https://sbi.co.in/documents/SCO_2026_advt.pdf",
    examPatternSlug: "sbi-so",
  },
  {
    id: "upd-9",
    updateDate: "28-09-2026",
    updateTime: "06:30 PM",
    isToday: false,
    category: "Notification",
    organization: "Defence Research & Development Organisation (DRDO)",
    boardShort: "Defence",
    postName: "DRDO CEPTAM-11 Senior Technical Assistant (STA-B) & Tech-A",
    vacancies: "2,045 Posts",
    vacanciesCount: 2045,
    qualification: "Diploma / B.Sc / ITI",
    lastDateOrExamDate: "Last Date: 30-10-2026",
    statusBadge: "R&D Defence",
    detailsUrl: "/job/drdo-ceptam-11",
    applyUrl: "https://www.drdo.gov.in/",
    pdfUrl: "https://www.drdo.gov.in/ceptam-11-notice.pdf",
    examPatternSlug: "drdo-ceptam",
  },
  {
    id: "upd-10",
    updateDate: "28-09-2026",
    updateTime: "05:10 PM",
    isToday: false,
    category: "Notification",
    organization: "Andhra Pradesh Public Service Commission (APPSC)",
    boardShort: "State PSC",
    postName: "APPSC Group-II Services (Executive & Non-Executive) Mains Date",
    vacancies: "897 Posts",
    vacanciesCount: 897,
    qualification: "Any Graduate",
    lastDateOrExamDate: "Mains Exam: 15-11-2026",
    statusBadge: "Mains Scheduled",
    detailsUrl: "/job/appsc-group2-2026",
    applyUrl: "https://psc.ap.gov.in/",
    pdfUrl: "https://psc.ap.gov.in/web/group2_mains_schedule.pdf",
    examPatternSlug: "appsc-group2",
  },
];
